#ifndef SHARE_H_INCLUDED

#define SHARE_H_INCLUDED

#define QUANTUM 1

#define SEED 654321

#define SIZEARRAY 100
#define NBPROCESSUS 10

#define EXECPERCENTAGE0 12
#define EXECPERCENTAGE1 11
#define EXECPERCENTAGE2 10
#define EXECPERCENTAGE3 9
#define EXECPERCENTAGE4 9
#define EXECPERCENTAGE5 9
#define EXECPERCENTAGE6 9
#define EXECPERCENTAGE7 8
#define EXECPERCENTAGE8 8
#define EXECPERCENTAGE9 8
#define EXECPERCENTAGE10 7

#define MAX_EXEC_T 20
#define PROBA_NEW_PROC 90

#endif
