#ifndef SHARE_H_INCLUDED

#define SHARE_H_INCLUDED

#define SIZEARRAY 100
#define NBPROCESSUS 53

#define EXECPERCENTAGE0 10
#define EXECPERCENTAGE1 9
#define EXECPERCENTAGE2 8
#define EXECPERCENTAGE3 7
#define EXECPERCENTAGE4 6
#define EXECPERCENTAGE5 5
#define EXECPERCENTAGE6 4
#define EXECPERCENTAGE7 3
#define EXECPERCENTAGE8 2
#define EXECPERCENTAGE9 1
#define EXECPERCENTAGE10 100

#endif